on: [push]
name: Deploy Tumbleweed Images to Azure Shared Gallery
jobs:
  deploy-tumbleweed-images:
    runs-on: ubuntu-latest
    steps:
    - name: Install Podman
      id: install
      run: sudo apt-get update && sudo apt-get -y install podman
    - name: Pull OpenSuse Mash Image
      id: pull
      run: podman pull registry.opensuse.org/virtualization/appliances/images/images_tw/opensuse/mash:latest
    - name: Run Container
      id: container
      run: podman run --cap-add CAP_SYS_ADMIN --rm -ti --name mash --volume ./publish:/mnt mash
    - name: Upload x86 Image
      id: x86
      run: mash account azure add --name azure --region centralus --source-container images --source-resource-group openSUSE --source-storage-account tumbleweedtest --credentials 
      
    
      
